[package]
name = "airgap"
version = "0.1.0"
edition = "2021"

[dependencies]
qrcode = "0.14"
image = "0.25"
clap = "4.5"
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
prost-build = "0.13"
